/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "xzctbfiozbtsnkvkbzjn"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Y3RiZmlvemJ0c25rdmtiempuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTcwNzksImV4cCI6MjA3MjI5MzA3OX0.RRd3QSPzDSxmmMP2KXd3rzk2D-d5K0cWIrp2eho7azk"